### ISSUE TITLE
why not push tornado_utils to pypi

### ISSUE THREAD

**Issue by ifduyue** [peterbe/tornado-utils#2]
that would be awesome

**Comment by peterbe** [comment]
It certainly would. I don't know why it isn't. I always include it as a git-submodule so that's why I maybe missed it. Also, there's not enough helpful people like you around :)

**Comment by ifduyue** [comment]
`python setup.py register` to register tornado_utils as pypi

`python setup.py sdist --formats=gztar,bztar,zip upload` to upload the release

**Comment by peterbe** [comment]
Got to fix the trove classifiers first.

**Comment by peterbe** [comment]
http://pypi.python.org/pypi/tornado-utils

**Comment by ifduyue** [comment]
nice job :)
