### ISSUE TITLE
typo at utils.encrypt_password

### ISSUE THREAD

**Issue by ifduyue** [peterbe/tornado-utils#3]
from https://github.com/peterbe/tornado-utils/blob/master/tornado_utils/utils.py#L46

``` python
def encrypt_password(raw_password, log_rounds=10):
    if not bcrypt:
        raise SystemError("bcrypt could no be imported")
    salt = bcrypt.gensalt(log_rounds=log_rounds)
    hsh = bcrypt.hashpw(raw_password, salt)
    algo = 'bcrypt'
    return u'%s$bcrypt$%s' % (algo, hsh)
```

since algo is "bcrypt" and "bcrypt" alreay in the string.
is it `return u'%s$%s$%s' % (salt, algo, hsh)` ?

**Comment by peterbe** [comment]
Fixed 
https://github.com/peterbe/tornado-utils/commit/e432b122dcdd9ff9723067c2aa23e50db35d4409
